server {
  listen 80;
  root /usr/share/nginx/html;
  client_max_body_size 512m;

  location /api/ {
    proxy_pass http://api:8080;
    proxy_http_version 1.1;
    proxy_read_timeout 120s;
    proxy_set_header Host $host;
    proxy_set_header X-Request-Id $request_id;
  }

  location /media/ {
    add_header Cache-Control "private, max-age=60";
    try_files $uri =404;
  }

  location / {
    try_files $uri $uri/ /index.html;
  }
}

